# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://rbrtwlz.github.io/fastai_object_detection/"

git_url = "https://github.com/rbrtwlz/fastai_object_detection/tree/master/"

def custom_doc_links(name): return None
