# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_dataloaders.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'